mod 'puppet/nginx'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/concat'
mod 'puppetlabs/translate'
mod 'samuelson-dockeragent', '1.0.0'
mod 'puppetlabs-docker', '3.13.0'
#mod 'samuelson/dockeragent'
#mod 'puppetlabs-docker'